Cesar Garcia Data Science

In [1]:
# Import libraries
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris


In [ ]:
# Load dataset to X and y

X, y = load_iris(return_X_y=True)


In [ ]:
# Load dataset into DataFrame

dataset = load_iris()
dfi = pd.DataFrame(dataset.data, columns=dataset.feature_names)
dfi['label'] = dataset.target
dfi.head()
# print(dataset.DESCR)

In [ ]:
# Description of dataset

print(dataset.DESCR)

In [ ]:
# Load dataset for preprocessing

df = pd.read_csv('train.csv')
df.head()

In [ ]:
# Create X and y
X = df.drop('Survived', axis=1)
y = df['Survived']


In [ ]:
# Split dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)


In [ ]:
# Import OrdinalEncoder
from sklearn.preprocessing import OrdinalEncoder


In [ ]:
# Instantiate preprocessing model
oe = OrdinalEncoder()


In [ ]:
# Fit and transform data into new column
oe.fit(X_train[['Pclass']])
X_train['Pclass_trans'] = oe.transform(X_train[['Pclass']])
X_train

In [ ]:
# Drop original column
X_train = X_train.drop('Pclass', axis=1)
X_train

In [ ]:
# Transform test data not fit
X_test['Pclass_trans'] = oe.transform(X_test[['Pclass']])


In [ ]:
# Drop original column from test data
X_test = X_test.drop('Pclass', axis=1)
X_test

In [ ]:
# Load MinMaxScaler range 0 to 1
from sklearn.preprocessing import MinMaxScaler
# Pass columns names in a list
colname = ['Age', 'Fare']
mms = MinMaxScaler()
X_ts = pd.DataFrame(mms.fit_transform(X_train[colname]), columns=['mms_Age', 'mms_Fare'])
X_ts = pd.concat([X_train, X_ts], axis=1)
X_ts = X_ts.drop(colname, axis=1)
X_ts

In [ ]:
# If all data is numerical you can use Normalizer
from sklearn.datasets import load_iris

iris = load_iris()
dfi = pd.DataFrame(data=iris.data, columns=iris.feature_names)
dfi.head(10)

In [ ]:
# Normalization l1 sum values is 1, l2 sum squared values is 1
from sklearn.preprocessing import Normalizer
norma = Normalizer(norm='l1')
dfnorma = pd.DataFrame(norma.fit_transform(dfi), columns=iris.feature_names)
dfnorma


In [ ]:
# Imputer import
from sklearn.impute import SimpleImputer

impage = SimpleImputer(missing_values=np.nan, strategy='mean', fill_value=None)

imp = impage.fit_transform(X_train[['Age']])

imp


In [22]:
# Iris classification
from sklearn.datasets import load_iris

dataset = load_iris()
# dfi = pd.DataFrame(dataset.data)
# dfi['label'] = dataset.target
# dfi.head()
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
# Set up ml model
X = dfi.drop(['label'], axis=1)
y = dfi['label']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [ ]:
# Import and instantiate model KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, weights='uniform', p=2, metric='minkowski')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)


In [ ]:
# Import and instantiate naive bayes
from sklearn.naive_bayes import GaussianNB
nb= GaussianNB()
# from sklearn.naive_bayes import MultinomialNB
# nb = MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
# from sklearn.naive_bayes import BernoulliNB
# nb = BernoulliNB()

nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)


In [18]:
# Import and instantiate DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=None, min_samples_split=2, min_samples_leaf=1, class_weight=None)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)


In [ ]:
# Import and instantiate model
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=1e5, solver='lbfgs', multi_class='auto', class_weight=None)
lr.fit(X_train, y_train)
y_pred =lr.predict(X_test)


In [19]:
# Metrics
from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))


0.9666666666666667
[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [4]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
137                6.4               3.1                5.5               1.8
84                 5.4               3.0                4.5               1.5
27                 5.2               3.5                1.5               0.2
127                6.1               3.0                4.9               1.8
132                6.4               2.8                5.6               2.2
..                 ...               ...                ...               ...
9                  4.9               3.1                1.5               0.1
103                6.3               2.9                5.6               1.8
67                 5.8               2.7                4.1               1.0
117                7.7               3.8                6.7               2.2
47                 4.6               3.2                1.4               0.2

[120 rows x 4 columns]

In [9]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
91                 6.1               3.0                4.6               1.4
135                7.7               3.0                6.1               2.3
69                 5.6               2.5                3.9               1.1
128                6.4               2.8                5.6               2.1
114                5.8               2.8                5.1               2.4
..                 ...               ...                ...               ...
133                6.3               2.8                5.1               1.5
137                6.4               3.1                5.5               1.8
72                 6.3               2.5                4.9               1.5
140                6.7               3.1                5.6               2.4
37                 4.9               3.6                1.4               0.1

[120 rows x 4 columns]